@extends('_layouts.main')

@section('body')

<!-- header -->
<div> 
    <div>
        <!-- navbar   -->
        @include('partials.nav')

        <!-- herosection -->
        <div class="relative max-w-7xl mx-auto mt-20 pb-20">
            <div class="flex flex-col justify-center items-center px-10 md:px-20">
                <h1 class="text-4xl font-bold">Privacy Policy</h1>
                <p class="text-xs mt-1">Effective date: 21/01/2024</p>

                <div class="max-w-4xl mx-auto mt-8 text-gray-700 pb-16 border-2 border-black p-10 rounded-xl mb-10">
                    <div>
                        <p class="mt-2">1. Introduction</p>
                        <p class="mt-2">
                            Welcome to Youform (“us”, “we”, or “our”) operates Youform (website/mobile application) (hereinafter referred to as “Service”). Our Privacy Policy governs your visit to Youform (website/mobile application), and explains how we collect, safeguard and disclose information that results from your use of our Service. 
                            We use your data to provide and improve Service. 
                            By using Service, you agree to the collection and use of information in accordance with this policy. 
                            Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions. 
                            Our Terms and Conditions (“Terms”) govern all use of our Service and together with the Privacy Policy constitute your agreement with us (“Agreement”).
                        </p>

                        <p class="mt-4">
                            2. Definitions
                        </p>
                        <p class="mt-2">
                            “Cookies” means small files stored on your device (computer or mobile device); <br>
                            “Data Controller” means a natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data; <br>
                            “Data Processors” or “Service Provider” means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively; <br>
                            “Data Subject” is any living individual who is the subject of Personal Data; <br>
                            “Location Data” shall have the meaning ascribed to it in Clause 4.3; <br>
                            “Personal Data” means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession); <br>
                            “Service” means the Youform (website/mobile application).; <br>
                            “Usage Data” means data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit); and <br>
                            “User(s)” means the person(s) using our Service and who corresponds to the Data Subject, which is the subject of Personal Data. <br>
                        </p>
                        
                        <p class="mt-4">3. Information Collection and Use</p>
                        <p class="mt-2">
                            We collect several different types of information for various purposes to provide and improve our Service to you.
                        </p>
                        
                        <p class="mt-4">
                            4. Types of Data Collected
                        </p>
                        <p class="mt-2">
                            <p>a. Personal Data</p><br>
                            <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:</p>
                            Email address; <br>
                            First name and last name; <br>
                            Phone number; <br>
                            Address, State, Province, ZIP/Postal code, City; and/or <br>
                            Cookies and Usage Data. We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or by emailing to hello@youform.io. <br>
                            <br>
                            <p>b. Usage Data</p> <br>
                            <p>
                                We may also collect information that your browser sends whenever you visit our Service or when you access Service by or through a mobile device.
                            This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                            When you access Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
                            </p>
                        </p>

                        <p class="mt-4">
                            5. Use of Data
                        </p>
                        
                        <p class="mt-2">
                            Youform uses the collected data for various purposes such as: <br>

                            <ol class="list-decimal list-inside">
                                <li>To provide and maintain our Service;</li>
                                <li>To notify you about changes to our Service;</li>
                                <li>To allow you to participate in interactive features of our Service when you choose to do so;</li>
                                <li>To provide customer support;</li>
                                <li>To gather analysis or valuable information so that we can improve our Service;</li>
                                <li>To monitor the usage of our Service;</li>
                                <li>To detect, prevent and address technical issues;</li>
                                <li>To fulfill any other purpose for which you provide it;</li>
                                <li>To carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</li>
                                <li>To provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;</li>
                                <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;</li>
                                <li>In any other way we may describe when you provide the information; and</li>
                                <li>For any other purpose with your consent.</li>
                            </ol>
                        </p>

                        <p class="mt-4">
                            6. Retention of Data
                        </p>
                        
                        <p class="mt-2">
                            We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
                            <br>
                            We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
                        </p>

                        <p class="mt-4">
                            7. Transfer of Data
                        </p>
                        
                        <p class="mt-2">
                            <ol class="list-decimal list-inside">
                                <li>Your information, including Personal Data, may be transferred to and maintained on computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</li>
                                <li>If you are located outside India and choose to provide information to us, please note that we transfer the data, including Personal Data, to India and process it there.</li>
                                <li>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</li>
                                <li>Youform will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</li>
                            </ol>
                        </p>

                        <p class="mt-4">
                            8. Payments
                        </p>
                        <p class="mt-2">
                            We may provide paid products and/or services within Service. In that case, we use third-party services for payment processing (e.g. payment processors).
                            <br>
                            We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy.
                        </p>

                        <p class="mt-4">
                            9. Changes to This Privacy Policy
                        </p>
                        <p class="mt-2">
                            We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
                            We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update “effective date” at the top of this Privacy Policy.
                            You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                        </p>

                        <p class="mt-4">
                            10. Contact Us
                        </p>
                        <p class="mt-2">
                            If you have any questions about this Privacy Policy, please contact us: hello@youform.io   
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>   

<!-- Faq -->
{{-- <div class="-mt-10 sm:-mt-16">
    <div class="pt-28 lg:pt-48 pb-20 bg-amber-50">
        <div class="relative max-w-7xl mx-auto -mt-16 pb-20">
            <div class="flex flex-col justify-center">
                <div class="">
                    <p class="text-center text-3xl sm:text-5xl xl:text-6xl font-bold mb-6 pt-10">
                        Frequently Asked Question
                    </p>
                </div>
                <div class="mt-10">
                    <div x-data="{ open: false }" class="border-y-2 border-black ">
                            <div class="w-4/5 mx-auto cursor-pointer" @click="open = !open">
                                <div  class="flex justify-between  px-4 py-10 text-3xl">
                                    <p class="text-black font-medium">Is Youform free?</p>
                                    <svg x-show="!open"  xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M19 9l-7 7-7-7" />
                                    </svg>
                                
                                    <svg x-show="open" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M5 15l7-7 7 7" />
                                      </svg>
                                </div>
                                <div x-show="open">
                                    <p class=" px-4 py-10 text-xl text-black">
                                        Youform is the best FREE alternative to Typeform in the market. While Typeform provides ONLY 10 responses in free account, Youform provides unlimited responses and forms in free account. 
                                    </p>
                                </div>   
                            </div>      
                    </div>
                    <div x-data="{ open: false }" class="border-y-2 border-black ">
                        <div class="w-4/5 mx-auto cursor-pointer" @click="open = !open">
                            <div  class="flex justify-between  px-4 py-10 text-3xl">
                                <p class="text-black font-medium">What is Youform PRO?</p>
                                <svg x-show="!open"  xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M19 9l-7 7-7-7" />
                                </svg>
                            
                                <svg x-show="open" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M5 15l7-7 7 7" />
                                  </svg>
                            </div>
                            <div x-show="open">
                                <p class=" px-4 py-10 text-xl text-black">
                                    Youform PRO provides you some advanced features like ability to invite team members, manage forms in workspaces, add your custom domain and remove Youform's branding from your forms.
                                </p>
                            </div>   
                        </div>      
                    </div>
                    <div x-data="{ open: false }" class="border-y-2 border-black ">
                        <div class="w-4/5 mx-auto cursor-pointer" @click="open = !open">
                            <div  class="flex justify-between  px-4 py-10 text-3xl">
                                <p class="text-black font-medium">Can I request some features?</p>
                                <svg x-show="!open"  xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M19 9l-7 7-7-7" />
                                </svg>
                            
                                <svg x-show="open" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="3">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M5 15l7-7 7 7" />
                                  </svg>
                            </div>
                            <div x-show="open">
                                <p class=" px-4 py-10 text-xl text-black">
                                    Sure, tweet or send us a DM <a href="https://twitter.com/youformio">@youformio</a> on tweeter and we would be happy to help!
                                </p>
                            </div>   
                        </div>      
                    </div>
                    
                </div>    
            </div>
                
            </div>
        </div>
    </div>
</div> --}}

@include('partials.footer')

@endsection
